/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPdfMergeRouteImport } from './routes/_authenticated/pdf-merge'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDataBlogRouteImport } from './routes/_authenticated/data/blog'
import { Route as AuthenticatedDataHeroRouteImport } from './routes/_authenticated/data/hero'
import { Route as AuthenticatedDataNowRouteImport } from './routes/_authenticated/data/now'
import { Route as AuthenticatedDataProjectsRouteImport } from './routes/_authenticated/data/projects'
import { Route as AuthenticatedDownloaderFacebookRouteImport } from './routes/_authenticated/downloader/facebook'
import { Route as AuthenticatedDownloaderYoutubeRouteImport } from './routes/_authenticated/downloader/youtube'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdfMergeRoute = AuthenticatedPdfMergeRouteImport.update({
  id: '/pdf-merge',
  path: '/pdf-merge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataBlogRoute = AuthenticatedDataBlogRouteImport.update({
  id: '/data/blog',
  path: '/data/blog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataHeroRoute = AuthenticatedDataHeroRouteImport.update({
  id: '/data/hero',
  path: '/data/hero',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataNowRoute = AuthenticatedDataNowRouteImport.update({
  id: '/data/now',
  path: '/data/now',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataProjectsRoute =
  AuthenticatedDataProjectsRouteImport.update({
    id: '/data/projects',
    path: '/data/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDownloaderFacebookRoute =
  AuthenticatedDownloaderFacebookRouteImport.update({
    id: '/downloader/facebook',
    path: '/downloader/facebook',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDownloaderYoutubeRoute =
  AuthenticatedDownloaderYoutubeRouteImport.update({
    id: '/downloader/youtube',
    path: '/downloader/youtube',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/pdf-merge': typeof AuthenticatedPdfMergeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/data/blog': typeof AuthenticatedDataBlogRoute
  '/data/hero': typeof AuthenticatedDataHeroRoute
  '/data/now': typeof AuthenticatedDataNowRoute
  '/data/projects': typeof AuthenticatedDataProjectsRoute
  '/downloader/facebook': typeof AuthenticatedDownloaderFacebookRoute
  '/downloader/youtube': typeof AuthenticatedDownloaderYoutubeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pdf-merge': typeof AuthenticatedPdfMergeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/data/blog': typeof AuthenticatedDataBlogRoute
  '/data/hero': typeof AuthenticatedDataHeroRoute
  '/data/now': typeof AuthenticatedDataNowRoute
  '/data/projects': typeof AuthenticatedDataProjectsRoute
  '/downloader/facebook': typeof AuthenticatedDownloaderFacebookRoute
  '/downloader/youtube': typeof AuthenticatedDownloaderYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/pdf-merge': typeof AuthenticatedPdfMergeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/data/blog': typeof AuthenticatedDataBlogRoute
  '/_authenticated/data/hero': typeof AuthenticatedDataHeroRoute
  '/_authenticated/data/now': typeof AuthenticatedDataNowRoute
  '/_authenticated/data/projects': typeof AuthenticatedDataProjectsRoute
  '/_authenticated/downloader/facebook': typeof AuthenticatedDownloaderFacebookRoute
  '/_authenticated/downloader/youtube': typeof AuthenticatedDownloaderYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pdf-merge'
    | '/profile'
    | '/data/blog'
    | '/data/hero'
    | '/data/now'
    | '/data/projects'
    | '/downloader/facebook'
    | '/downloader/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pdf-merge'
    | '/profile'
    | '/'
    | '/data/blog'
    | '/data/hero'
    | '/data/now'
    | '/data/projects'
    | '/downloader/facebook'
    | '/downloader/youtube'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/pdf-merge'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/data/blog'
    | '/_authenticated/data/hero'
    | '/_authenticated/data/now'
    | '/_authenticated/data/projects'
    | '/_authenticated/downloader/facebook'
    | '/_authenticated/downloader/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdf-merge': {
      id: '/_authenticated/pdf-merge'
      path: '/pdf-merge'
      fullPath: '/pdf-merge'
      preLoaderRoute: typeof AuthenticatedPdfMergeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/blog': {
      id: '/_authenticated/data/blog'
      path: '/data/blog'
      fullPath: '/data/blog'
      preLoaderRoute: typeof AuthenticatedDataBlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/hero': {
      id: '/_authenticated/data/hero'
      path: '/data/hero'
      fullPath: '/data/hero'
      preLoaderRoute: typeof AuthenticatedDataHeroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/now': {
      id: '/_authenticated/data/now'
      path: '/data/now'
      fullPath: '/data/now'
      preLoaderRoute: typeof AuthenticatedDataNowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/projects': {
      id: '/_authenticated/data/projects'
      path: '/data/projects'
      fullPath: '/data/projects'
      preLoaderRoute: typeof AuthenticatedDataProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloader/facebook': {
      id: '/_authenticated/downloader/facebook'
      path: '/downloader/facebook'
      fullPath: '/downloader/facebook'
      preLoaderRoute: typeof AuthenticatedDownloaderFacebookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloader/youtube': {
      id: '/_authenticated/downloader/youtube'
      path: '/downloader/youtube'
      fullPath: '/downloader/youtube'
      preLoaderRoute: typeof AuthenticatedDownloaderYoutubeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPdfMergeRoute: typeof AuthenticatedPdfMergeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDataBlogRoute: typeof AuthenticatedDataBlogRoute
  AuthenticatedDataHeroRoute: typeof AuthenticatedDataHeroRoute
  AuthenticatedDataNowRoute: typeof AuthenticatedDataNowRoute
  AuthenticatedDataProjectsRoute: typeof AuthenticatedDataProjectsRoute
  AuthenticatedDownloaderFacebookRoute: typeof AuthenticatedDownloaderFacebookRoute
  AuthenticatedDownloaderYoutubeRoute: typeof AuthenticatedDownloaderYoutubeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPdfMergeRoute: AuthenticatedPdfMergeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDataBlogRoute: AuthenticatedDataBlogRoute,
  AuthenticatedDataHeroRoute: AuthenticatedDataHeroRoute,
  AuthenticatedDataNowRoute: AuthenticatedDataNowRoute,
  AuthenticatedDataProjectsRoute: AuthenticatedDataProjectsRoute,
  AuthenticatedDownloaderFacebookRoute: AuthenticatedDownloaderFacebookRoute,
  AuthenticatedDownloaderYoutubeRoute: AuthenticatedDownloaderYoutubeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
